# Generated by Django 4.0.5 on 2022-06-08 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id_proposal', models.IntegerField(primary_key=True, serialize=False)),
                ('proposal_title_es', models.CharField(max_length=255)),
                ('proposal_title_en', models.CharField(max_length=255)),
                ('proposal_title_fr', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supports', models.ManyToManyField(to='stats.proposal')),
            ],
        ),
    ]
